### ISSUE TITLE
Refine `build` and `release build`/`build-distribute` commands for Git operations

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-release#15]
Between "release prepare <version>" and "release conclude <version>", it would be nice to do a "build <version>" command. This is the version that WILL BE tagged, right before the tagging step happens. Doing a "mvn clean install" against this version would be nice as a way to fail faster if something is wrong.

However, the following issues preclude this from happening:
* "build <version>" actually does a `git.prepare` operation before doing the build. We'd need a command option (`@CliOption(key="in-place") Boolean inPlace`) that lets us skip over this and simply do the build job on all the modules.
* Even with this option plugged in, for some reason, Jenkins would get stuck on SD MongoDB. I didn't have time to investigate why this build would stall out for over an hour.

Either we need to uncover what is going wrong so we can bring in this extra check, or we need an alternative way to do "mvn verify" on every module in the `BuildCommands`.

**Comment by mp911de** [comment]
We should remove the Git interaction of the `build $TRAINITERATION` command. Same goes for the `build-distribute` command. Instead, we should turn our `release build` command into something that checks out the tag before building. It would follow a much more natural pattern that releases are tag-based.
