### ISSUE TITLE
Introduce assertion that a given release tag is really a tag

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-release#16]
When performing a `git co-tag` operation, it would be nice to assert that this is REALLY a tag before moving forward.

@mp911de said: "in the git operations, also, you need to translate the train iteration into individual versions and then tag names".

I frankly don't understand this. I tried to look through the metadata, and couldn't see what exactly a train-level tag is nor what to check it against.

**Comment by mp911de** [comment]
We need a method like `checkout(Project, TrainIteration)` that makes use of `findTagFor(…)`. `checkout(Project, Branch)` uses branch names (`a.b.x`) as checkout targets already. Having a similar method to checkout tags is what we're looking for.

**Comment by mp911de** [comment]
`git co` does that already.
