### ISSUE TITLE
The Reference Doc URL for Spring Data project points to Spring Data Build

### ISSUE THREAD

**Issue by runbing** [spring-projects/spring-data-release#72]
The "**Reference Doc**" in the "[**LEARN**](https://spring.io/projects/spring-data#learn)" section of the Spring Data documentation has a incorrect URL, which I cannot find where correct it with a PR. The current URL is: https://docs.spring.io/spring-data/build/reference/, and it should be: https://docs.spring.io/spring-data/commons/reference/.

**Comment by mp911de** [comment]
Thanks a lot. That's fixed now. Appreciate your support also on the other pull requests.
