### ISSUE TITLE
Broken documentation link for SNAPSHOT version

### ISSUE THREAD

**Issue by breun** [spring-projects/spring-data-release#91]
On https://spring.io/projects/spring-data-jdbc#learn 3.3.3-SNAPSHOT links to https://docs.spring.io/spring-data/relational/reference/3.3/, which redirects to https://docs.spring.io/spring-data/relational/reference/, which displays the documentation for version 3.3.2.

It looks like https://docs.spring.io/spring-data/relational/reference/${version} is the correct URL template, because this works:

* 3.3.3-SNAPSHOT: https://docs.spring.io/spring-data/relational/reference/3.3.3-SNAPSHOT

A similar issue exists for the SNAPSHOT versions on these Spring Data documentation overview pages:

* https://spring.io/projects/spring-data-jpa#learn
* https://spring.io/projects/spring-data-ldap#learn
* https://spring.io/projects/spring-data-mongodb#learn
* https://spring.io/projects/spring-data-redis#learn
* https://spring.io/projects/spring-data-r2dbc#learn
* https://spring.io/projects/spring-data-rest#learn
* https://spring.io/projects/spring-data-cassandra#learn
* https://spring.io/projects/spring-data-couchbase#learn
* https://spring.io/projects/spring-data-elasticsearch#learn
* https://spring.io/projects/spring-data-neo4j#learn

**Comment by mp911de** [comment]
Thanks a lot, that's fixed now.
